name: Build and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_APP_ID: ${{secrets.REACT_APP_APP_ID}}
      REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}
      REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN}}
      REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID}}
      REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET}}
      REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID}}
      REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID}}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Generate 200.html
        run: cp build/index.html build/200.html
      - name: Deploy to surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'https://social-react-app.surge.sh/'
          project: 'build'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
